--select * into timezone_bak from timezone

Update timezone Set AlternateTimeZoneInfoId = 'Etc/GMT+12' WHERE timezone_nm = '(UTC-12:00) International Date Line West'
Update timezone Set AlternateTimeZoneInfoId = 'Etc/GMT+11' WHERE timezone_nm = '(UTC-11:00) Coordinated Universal Time-11'
Update timezone Set AlternateTimeZoneInfoId = 'Etc/GMT+10' WHERE timezone_nm = '(UTC-10:00) Hawaii'
Update timezone Set AlternateTimeZoneInfoId = 'America/Anchorage' WHERE timezone_nm = '(UTC-09:00) Alaska'
Update timezone Set AlternateTimeZoneInfoId = 'America/Santa_Isabel' WHERE timezone_nm = '(UTC-08:00) Baja California'
Update timezone Set AlternateTimeZoneInfoId = 'America/Dawson' WHERE timezone_nm = '(UTC-08:00) Pacific Time (US & Canada)'
Update timezone Set AlternateTimeZoneInfoId = 'America/Creston' WHERE timezone_nm = '(UTC-07:00) Arizona'
Update timezone Set AlternateTimeZoneInfoId = 'America/Chihuahua' WHERE timezone_nm = '(UTC-07:00) Chihuahua, La Paz, Mazatlan'
Update timezone Set AlternateTimeZoneInfoId = 'America/Boise' WHERE timezone_nm = '(UTC-07:00) Mountain Time (US & Canada)'
Update timezone Set AlternateTimeZoneInfoId = 'America/Belize' WHERE timezone_nm = '(UTC-06:00) Central America'
Update timezone Set AlternateTimeZoneInfoId = 'America/Chicago' WHERE timezone_nm = '(UTC-06:00) Central Time (US & Canada)'
Update timezone Set AlternateTimeZoneInfoId = 'America/Bahia_Banderas' WHERE timezone_nm = '(UTC-06:00) Guadalajara, Mexico City, Monterrey'
Update timezone Set AlternateTimeZoneInfoId = 'America/Regina' WHERE timezone_nm = '(UTC-06:00) Saskatchewan'
Update timezone Set AlternateTimeZoneInfoId = 'America/Detroit' WHERE timezone_nm = '(UTC-05:00) Eastern Time (US & Canada)'
Update timezone Set AlternateTimeZoneInfoId = 'America/Indiana/Marengo' WHERE timezone_nm = '(UTC-05:00) Indiana (East)'
Update timezone Set AlternateTimeZoneInfoId = 'America/Caracas' WHERE timezone_nm = '(UTC-04:30) Caracas'
Update timezone Set AlternateTimeZoneInfoId = 'America/Asuncion' WHERE timezone_nm = '(UTC-04:00) Asuncion'
Update timezone Set AlternateTimeZoneInfoId = 'America/Glace_Bay' WHERE timezone_nm = '(UTC-04:00) Atlantic Time (Canada)'
Update timezone Set AlternateTimeZoneInfoId = 'America/Santiago' WHERE timezone_nm = '(UTC-04:00) Santiago'
Update timezone Set AlternateTimeZoneInfoId = 'America/Sao_Paulo' WHERE timezone_nm = '(UTC-03:00) Brasilia'
Update timezone Set AlternateTimeZoneInfoId = 'America/Argentina/La_Rioja' WHERE timezone_nm = '(UTC-03:00) Buenos Aires'
Update timezone Set AlternateTimeZoneInfoId = 'America/Araguaina' WHERE timezone_nm = '(UTC-03:00) Cayenne, Fortaleza'
Update timezone Set AlternateTimeZoneInfoId = 'America/Godthab' WHERE timezone_nm = '(UTC-03:00) Greenland'
Update timezone Set AlternateTimeZoneInfoId = 'America/Montevideo' WHERE timezone_nm = '(UTC-03:00) Montevideo'
Update timezone Set AlternateTimeZoneInfoId = 'America/Bahia' WHERE timezone_nm = '(UTC-03:00) Salvador'
Update timezone Set AlternateTimeZoneInfoId = 'America/Noronha' WHERE timezone_nm = '(UTC-02:00) Coordinated Universal Time-02'
Update timezone Set AlternateTimeZoneInfoId = 'America/Scoresbysund' WHERE timezone_nm = '(UTC-01:00) Azores'
Update timezone Set AlternateTimeZoneInfoId = 'Atlantic/Cape_Verde' WHERE timezone_nm = '(UTC-01:00) Cape Verde Is.'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Casablanca' WHERE timezone_nm = '(UTC) Casablanca'
Update timezone Set AlternateTimeZoneInfoId = 'America/Danmarkshavn' WHERE timezone_nm = '(UTC) Coordinated Universal Time'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Abidjan' WHERE timezone_nm = '(UTC) Monrovia, Reykjavik'
Update timezone Set AlternateTimeZoneInfoId = 'Arctic/Longyearbyen' WHERE timezone_nm = '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna'
Update timezone Set AlternateTimeZoneInfoId = 'Europe/Belgrade' WHERE timezone_nm = '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Ceuta' WHERE timezone_nm = '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris'
Update timezone Set AlternateTimeZoneInfoId = 'Europe/Sarajevo' WHERE timezone_nm = '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Algiers' WHERE timezone_nm = '(UTC+01:00) West Central Africa'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Windhoek' WHERE timezone_nm = '(UTC+01:00) Windhoek'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Nicosia' WHERE timezone_nm = '(UTC+02:00) Athens, Bucharest'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Beirut' WHERE timezone_nm = '(UTC+02:00) Beirut'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Cairo' WHERE timezone_nm = '(UTC+02:00) Cairo'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Damascus' WHERE timezone_nm = '(UTC+02:00) Damascus'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Nicosia' WHERE timezone_nm = '(UTC+02:00) E. Europe'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Blantyre' WHERE timezone_nm = '(UTC+02:00) Harare, Pretoria'
Update timezone Set AlternateTimeZoneInfoId = 'Europe/Helsinki' WHERE timezone_nm = '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Jerusalem' WHERE timezone_nm = '(UTC+02:00) Jerusalem'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Tripoli' WHERE timezone_nm = '(UTC+02:00) Tripoli'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Baghdad' WHERE timezone_nm = '(UTC+03:00) Baghdad'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Aden' WHERE timezone_nm = '(UTC+03:00) Kuwait, Riyadh'
Update timezone Set AlternateTimeZoneInfoId = 'Africa/Addis_Ababa' WHERE timezone_nm = '(UTC+03:00) Nairobi'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Tehran' WHERE timezone_nm = '(UTC+03:30) Tehran'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Dubai' WHERE timezone_nm = '(UTC+04:00) Abu Dhabi, Muscat'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Baku' WHERE timezone_nm = '(UTC+04:00) Baku'
Update timezone Set AlternateTimeZoneInfoId = 'Indian/Mahe' WHERE timezone_nm = '(UTC+04:00) Port Louis'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Tbilisi' WHERE timezone_nm = '(UTC+04:00) Tbilisi'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Yerevan' WHERE timezone_nm = '(UTC+04:00) Yerevan'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Kabul' WHERE timezone_nm = '(UTC+04:30) Kabul'
Update timezone Set AlternateTimeZoneInfoId = 'Antarctica/Mawson' WHERE timezone_nm = '(UTC+05:00) Ashgabat, Tashkent'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Karachi' WHERE timezone_nm = '(UTC+05:00) Islamabad, Karachi'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Kolkata' WHERE timezone_nm = '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Colombo' WHERE timezone_nm = '(UTC+05:30) Sri Jayawardenepura'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Kathmandu' WHERE timezone_nm = '(UTC+05:45) Kathmandu'
Update timezone Set AlternateTimeZoneInfoId = 'Antarctica/Davis' WHERE timezone_nm = '(UTC+07:00) Bangkok, Hanoi, Jakarta'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Novokuznetsk' WHERE timezone_nm = '(UTC+07:00) Novosibirsk'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Hong_Kong' WHERE timezone_nm = '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Krasnoyarsk' WHERE timezone_nm = '(UTC+08:00) Krasnoyarsk'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Brunei' WHERE timezone_nm = '(UTC+08:00) Kuala Lumpur, Singapore'
Update timezone Set AlternateTimeZoneInfoId = 'Antarctica/Casey' WHERE timezone_nm = '(UTC+08:00) Perth'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Taipei' WHERE timezone_nm = '(UTC+08:00) Taipei'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Choibalsan' WHERE timezone_nm = '(UTC+08:00) Ulaanbaatar'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Dili' WHERE timezone_nm = '(UTC+09:00) Osaka, Sapporo, Tokyo'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Pyongyang' WHERE timezone_nm = '(UTC+09:00) Seoul'
Update timezone Set AlternateTimeZoneInfoId = 'Australia/Adelaide' WHERE timezone_nm = '(UTC+09:30) Adelaide'
Update timezone Set AlternateTimeZoneInfoId = 'Australia/Darwin' WHERE timezone_nm = '(UTC+09:30) Darwin'
Update timezone Set AlternateTimeZoneInfoId = 'Australia/Brisbane' WHERE timezone_nm = '(UTC+10:00) Brisbane'
Update timezone Set AlternateTimeZoneInfoId = 'Australia/Melbourne' WHERE timezone_nm = '(UTC+10:00) Canberra, Melbourne, Sydney'
Update timezone Set AlternateTimeZoneInfoId = 'Antarctica/DumontDUrville' WHERE timezone_nm = '(UTC+10:00) Guam, Port Moresby'
Update timezone Set AlternateTimeZoneInfoId = 'Australia/Currie' WHERE timezone_nm = '(UTC+10:00) Hobart'
Update timezone Set AlternateTimeZoneInfoId = 'Antarctica/Macquarie' WHERE timezone_nm = '(UTC+11:00) Solomon Is., New Caledonia'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Sakhalin' WHERE timezone_nm = '(UTC+11:00) Vladivostok'
Update timezone Set AlternateTimeZoneInfoId = 'Antarctica/McMurdo' WHERE timezone_nm = '(UTC+12:00) Auckland, Wellington'
Update timezone Set AlternateTimeZoneInfoId = 'Etc/GMT-12' WHERE timezone_nm = '(UTC+12:00) Coordinated Universal Time+12'
Update timezone Set AlternateTimeZoneInfoId = 'Pacific/Fiji' WHERE timezone_nm = '(UTC+12:00) Fiji'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Anadyr' WHERE timezone_nm = '(UTC+12:00) Magadan'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Kamchatka' WHERE timezone_nm = '(UTC+12:00) Petropavlovsk-Kamchatsky - Old'
Update timezone Set AlternateTimeZoneInfoId = 'Asia/Dhaka' WHERE timezone_nm = '(UTC+06:00) Dhaka'
